- name: This sets up an httpd webserver
  hosts: ubuntu
  become: yes
  remote_user: ubuntu
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/rs-mum-9.pem"  
    ansible_ssh_user: "ubuntu"
  tasks:
  - name: "Install nginx and php packages"
    package:
        name:
          - "nginx"
          - "php"
        state: present
  - name: "copy code "
    copy:
        src: index.php
        dest: "/var/www/html/index.php"
  - name: "Start httpd services"
    service:
        name: httpd
        state: started
  - name: Yum Install Packages
    apt: name={{item}} state=latest
    with_items:
      - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
