- name: This sets up an nginx webserver
  hosts: all
  become: yes
  gather_facts: true

  tasks:
  - name: update cache in ubuntu
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
      
  - name: nginx installation on ubuntu
    apt:
      name: nginx
      state: latest
    when: ansible_os_family == "Debian"
 
  - name: nginx server start 
    service:
      name: nginx
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
  - name: "copy code "
    copy:
        src: index.php
        dest: "/var/www/html/index.php"
  - name: "copy index page "
    copy:
        src: index.html
        dest: "/var/www/html/index.html"
  - name: apt Install Packages
    apt: name={{item}} state=latest
    with_items:
      - wget

