- name: This sets up an nginx webserver
  hosts: ubuntu
  become: yes
  gather_facts: true
  tasks:
  - name: update cache in ubuntu
    apt:
      update_cache: yes
  - name: "Install nginx and php packages"
    package:
        name:
          - "nginx"
          - "php"
        state: present
  - name: "copy code "
    copy:
        src: index.php
        dest: "/var/www/html/index.php"
  - name: "Start httpd services"
    service:
      name: nginx
      state: started
  - name: apt Install Packages
    apt: name={{item}} state=latest
    with_items:
      - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
