- name: This sets up an nginx webserver
  hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: update apt list
    shell: sudo apt update -y
  - name: update cache in ubuntu
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
      
  - name: apche2 installation on ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"
 
  - name: apache2 server start 
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
  - name: "copy code "
    copy:
        src: index.php
        dest: "/var/www/html/index.php"
  - name: apt Install Packages
    apt: name={{item}} state=latest
    with_items:
      - wget

